open("/home/travis/Desktop/PHYS 345/Mini_Project/EYE-Retinal-Detachment.jpg");
run("Duplicate...", " ");
run("Duplicate...", " ");
selectWindow("EYE-Retinal-Detachment.jpg");
close();
run("8-bit");
selectWindow("EYE-Retinal-Detachment-1.jpg");
run("8-bit");
selectWindow("EYE-Retinal-Detachment-2.jpg");
saveAs("Tiff", "/home/travis/Desktop/PHYS 345/Mini_Project/Retinal_Detachment/EYE-Retinal-Detachment-2.tif");
selectWindow("EYE-Retinal-Detachment-1.jpg");
run("Mean...", "radius=40");
saveAs("Tiff", "/home/travis/Desktop/PHYS 345/Mini_Project/Retinal_Detachment/EYE-Retinal-Detachment-Background.tif");
selectWindow("EYE-Retinal-Detachment-2.tif");
imageCalculator("Subtract create", "EYE-Retinal-Detachment-Background.tif","EYE-Retinal-Detachment-2.tif");
selectWindow("Result of EYE-Retinal-Detachment-Background.tif");
//run("Brightness/Contrast...");
run("Apply LUT");
saveAs("Tiff", "/home/travis/Desktop/PHYS 345/Mini_Project/Retinal_Detachment/SubtractionOfBackgroundAndContrast.tif");
run("Close");
