open("/home/travis/Desktop/30_test_noiseElimination/30_training.tif");
run("Duplicate...", " ");
run("Duplicate...", " ");
selectWindow("30_training.tif");
close();
selectWindow("30_training-1.tif");
run("8-bit");
selectWindow("30_training-2.tif");
run("8-bit");
run("Mean...", "radius=45");
saveAs("Tiff", "/home/travis/Desktop/30_test_noiseElimination/30_training-Background.tif");
selectWindow("30_training-1.tif");
saveAs("Tiff", "/home/travis/Desktop/30_test_noiseElimination/30_training-1.tif");
imageCalculator("Subtract create", "30_training-Background.tif","30_training-1.tif");
selectWindow("Result of 30_training-Background.tif");
//run("Brightness/Contrast...");
run("Apply LUT");
saveAs("Tiff", "/home/travis/Desktop/30_test_noiseElimination/ResultOfBackgroundSubtraction.tif");
run("Close");
run("Duplicate...", " ");
run("Convolve...", "text1=[1 1 1\n1 9 1\n1 1 1\n] normalize");
//run("Brightness/Contrast...");
saveAs("Tiff", "/home/travis/Desktop/30_test_noiseElimination/SmoothingMaskResult.tif");
selectWindow("ResultOfBackgroundSubtraction.tif");
run("Duplicate...", " ");
run("Gaussian Blur...", "sigma=2");
//run("Brightness/Contrast...");
run("Apply LUT");
run("Close");
saveAs("Tiff", "/home/travis/Desktop/30_test_noiseElimination/GausianBlurResult.tif");
