open("/home/travis/Desktop/PHYS 345/Mini_Project/25_training.tif");
run("Duplicate...", " ");
selectWindow("25_training.tif");
run("Duplicate...", " ");
selectWindow("25_training.tif");
close();
run("8-bit");
selectWindow("25_training-1.tif");
run("8-bit");
selectWindow("25_training-2.tif");
selectWindow("25_training-1.tif");
run("Mean...", "radius=25");
saveAs("Tiff", "/home/travis/Desktop/PHYS 345/Mini_Project/25_test/25_training-1-Background.tif");
selectWindow("25_training-2.tif");
saveAs("Tiff", "/home/travis/Desktop/PHYS 345/Mini_Project/25_test/25_training-2.tif");
imageCalculator("Subtract create", "25_training-1-Background.tif","25_training-2.tif");
selectWindow("Result of 25_training-1-Background.tif");
selectWindow("25_training-2.tif");
selectWindow("Result of 25_training-1-Background.tif");
//run("Brightness/Contrast...");
run("Apply LUT");
run("Close");
saveAs("Tiff", "/home/travis/Desktop/PHYS 345/Mini_Project/25_test/ResultOfSubtractingBackground.tif");
run("Save");
run("Duplicate...", " ");
selectWindow("ResultOfSubtractingBackground-1.tif");
run("Convolve...", "text1=[1 1 1\n1 9 1\n1 1 1\n] normalize");
saveAs("Tiff", "/home/travis/Desktop/PHYS 345/Mini_Project/25_test/ResultOfSubtractingBackground-ConvolvedWithSmoothingKernel.tif");

