open("/home/travis/Desktop/PHYS 345/Mini_Project/05_test.tif");
run("Duplicate...", " ");
run("Duplicate...", " ");
selectWindow("05_test.tif");
close();
run("8-bit");
selectWindow("05_test-1.tif");
run("8-bit");
selectWindow("05_test-2.tif");
selectWindow("05_test-1.tif");
saveAs("Tiff", "/home/travis/Desktop/PHYS 345/Mini_Project/05_test/05_test-1.tif");
selectWindow("05_test-2.tif");
run("Mean...", "radius=40");
saveAs("Tiff", "/home/travis/Desktop/PHYS 345/Mini_Project/05_test/05_test-Background.tif");
imageCalculator("Subtract create", "05_test-Background.tif","05_test-1.tif");
selectWindow("Result of 05_test-Background.tif");
selectWindow("05_test-Background.tif");
selectWindow("Result of 05_test-Background.tif");
//run("Brightness/Contrast...");
run("Apply LUT");
saveAs("Tiff", "/home/travis/Desktop/PHYS 345/Mini_Project/05_test/ResultOfSubtractingBackground.tif");
run("Close");
run("Save");
run("Duplicate...", " ");
selectWindow("ResultOfSubtractingBackground-1.tif");
run("Convolve...", "text1=[1 1 1\n1 9 1\n1 1 1\n] normalize");
//run("Brightness/Contrast...");
run("Apply LUT");
saveAs("Tiff", "/home/travis/Desktop/PHYS 345/Mini_Project/05_test/ResultOfSubtractingBackground-ConvolvedWithSmoothingKernel.tif");
