open("/home/travis/Desktop/PHYS 345/Mini_Project/12_test.tif");
run("Duplicate...", " ");
selectWindow("12_test.tif");
selectWindow("12_test-1.tif");
run("Duplicate...", " ");
selectWindow("12_test-2.tif");
selectWindow("12_test-1.tif");
selectWindow("12_test.tif");
close();
run("8-bit");
selectWindow("12_test-2.tif");
run("8-bit");
run("Mean...", "radius=40");

selectWindow("12_test-1.tif");
saveAs("Tiff", "/home/travis/Desktop/PHYS 345/Mini_Project/12_test/12_test-1.tif");
selectWindow("12_test-2.tif");
saveAs("Tiff", "/home/travis/Desktop/PHYS 345/Mini_Project/12_test/12_test-Background.tif");
imageCalculator("Subtract create", "12_test-Background.tif","12_test-1.tif");
selectWindow("Result of 12_test-Background.tif");
//run("Brightness/Contrast...");
run("Apply LUT");
saveAs("Tiff", "/home/travis/Desktop/PHYS 345/Mini_Project/12_test/ResultOfSubtractingBackground.tif");
run("Duplicate...", " ");
selectWindow("ResultOfSubtractingBackground.tif");
selectWindow("ResultOfSubtractingBackground-1.tif");
run("Convolve...", "text1=[1 1 1\n1 9 1\n1 1 1\n] normalize");

//run("Brightness/Contrast...");
run("Apply LUT");
run("Close");
saveAs("Tiff", "/home/travis/Desktop/PHYS 345/Mini_Project/12_test/ResultOfSubtractingBackground-ConvolvedWithSmoothingKernel.tif");
